name: run-tests
on: [push, pull_request]
run-name: Running Matlab tests on ${{ github.ref_name }}
jobs:
  my-job:
    name: Run MATLAB Tests and Generate Artifacts
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v1
        with:
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
          source-folder: src
